#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

eventlist:
    path: /events/{slug}
    controller: App\Controller\EventListController::list

allevents:
    path: /events/
    controller: App\Controller\EventListController::all