#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\HomeController::index

userlogin:
    path: /login
    controller: App\Controller\SecurityController::login

userlogout:
    path: /logout
    controller: App\Controller\SecurityController::logout

uregister:
    path: /register
    controller: App\Controller\RegistrationController::register

eventlist:
    path: /events/{slug}
    controller: App\Controller\EventListController::list

allevents:
    path: /events/
    controller: App\Controller\EventListController::all